disabled = false
languageCode = "en"  #文字编码
languageName = "English"  #多语言显示名称
weight = 1
title = "BlueyASI"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "logo1.png" #夜晚模式LOGO
  # secondaryLogo = "logo2.png" #白天模式LOGO
  description = "Super AI for Human Evolution & Civilization Advancement."

[params.author]
  image = "logo3.png" #首页中心LOGO
  name = "Bluey Artificial Super Intelligence" #首页中间LOGO下名称
  email = "ohulab.org@gmail.com"
  headline = "For Human Evolution & Civilization Advancement."   #首页标语
  bio = "For Human Evolution & Civilization Advancement."   #文章页LOGO下说明标语
  links = [
    { x-twitter = "https://x.com/BlueyASI_org" },
    { bluesky = "#" },
    { facebook = "#" },
    { instagram = "#" },
    { telegram = "#" },
    { github = "#" },
  ]  #文章页作者LOGO下社交媒体图标连接
