disabled = false
languageCode = "zh-cn"  #文字编码
languageName = "简体中文"  #多语言显示名称
weight = 2
title = "BlueyASI"

[params]
  displayName = "简体中文"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "logo1.png" #夜晚模式LOGO
  # secondaryLogo = "logo2.png" #白天模式LOGO
  description = "构建帮助人类进化与文明升级的超级人工智能"

[params.author]
  image = "logo3.png" #首页中心LOGO
  name = "蔚蓝超级人工智能" #首页中间LOGO下大字名称
  email = "ohulab.org@gmail.com"
  headline = "构建帮助人类进化与文明升级的超级人工智能"   #首页标语
  bio = "构建帮助人类进化与文明升级的超级人工智能"   #文章页作者图标下说明标语
  links = [
    { x-twitter = "#" },
    { bluesky = "#" },
    { facebook = "#" },
    { instagram = "#" },
    { telegram = "#" },
    { github = "#" },
  ]  #文章页作者LOGO下社交媒体图标连接
